-- Your SQL goes here
-- create table trash_days (
--   id integer primary key,
--   trash_type varchar
--   -- trash_type varchar primary,
--   -- nth integer not null primary,
--   -- day varchar not null primary
-- )